import "@/app/globals.css";
import ReduxProvider from "@/state/reducers/ReduxProvider";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body>
          <ToastContainer />
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
